@startuml
    abstract class User {
        - first_name : string
        - last_name : string
        - email : string
        - password : string
        - created_at : DateTime
    }

    enum UserRole{
        ADMIN,
        AUTHOR,
        READER
    }

    class Reader {
        - role : UserRole
    }

    class Author {
        - role : UserRole
    }

    class Admin {
        - role : UserRole
    }


    class Article {
        - title : string
        - content : text
        - cover : string
        - created_at: DateTime
        - likes_count : int
        - comments_count : int
    }


    class Comment {
        - body : text
        - created_at : DateTime
    }

    class Like {
        - created_at : DateTime
        - likes_count : int
    }

    interface Likable {
    }

    class Category {
        - name : string
        - description: text
        - articles_count : int
    }

    interface Reportable {
    }

    class Report {
        - message: ReportReason
        - created_at: Date
    }

    enum ReportReason{
        SPAM,
        EXPLICIT_CONTENT,
        INSULT,
        RACIST_CONTENT,
        OFFENSIVE,
        ABUSE,
        COPYRIGHT,
        OTHER
    }

    User <|--- Reader
    User <|--- Admin
    User <|--- Author

    Reader -- UserRole
    Admin -- UserRole
    Author -- UserRole

    Likable <|.. Article
    Likable <|.. Comment

    Reportable <|.. Article
    Reportable <|.. Comment


    Article "0..*" -- "1..1" Author : belongs to >
    Article "0..*" -- "*..*" Category : belongs to many >
    (Article, Category) .. ArticleCategory
    Comment "0..*" -- "1..1" Reader : belongs to >
    Comment "0..*" -- "1..1" Article : has <
    Reader "1..1" -- "0..*" Like : creates
    Like "0..*" -- "1..1" Likable : targets
    Reader "1..1" -- "0..*" Report : creates
    Report "0..*" -- "1..1" Reportable : targets
    Report -- ReportReason


@endumlb